version: '3'
services:
  shell:
    build: .
    image: redowildsafari
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    volumes:
      - ./chris:/app
      - ./mysql:/var/lib/mysql

  web:
    image: redowildsafari
    stdin_open: true
    tty: true
    ports:
      - "8008:80"
    entrypoint: /bin/bash run.sh
    volumes:
      - ./chris:/app
      - ./mysql:/var/lib/mysql
